import type { Metadata } from 'next';
import Navbar from '@/components/sections/Navbar';
import { Geist_Mono, IBM_Plex_Sans } from 'next/font/google';
import './globals.css';

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-ibm-plex-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="bg-[url('/background.jpg')] bg-repeat bg-center bg-[length:auto]">
          {children}
        </div>
      </body>
    </html>
  );
}
